### PR TITLE
General code improvement

### PR DESCRIPTION
**Pull request by RoKondo**
Code under shellcheck guidelines

### CODE REVIEW

**Review by mikedupuis — COMMENTED** [review]
Overall these changes are great, and I will merge the PR. One quick question: you changed some variable uses from ${foo} to $foo. Why do you prefer that format?

**Comment by RoKondo** [comment]
Until now I haven't had a problem with using "$foo", nor the need to use ${foo}. so I keep using "$foo" but I will check out the use of ${} if make sense I can "correct" this

**Comment by mikedupuis** [comment]
The {} format will help with concatenation when one part of the value is variable and one part is fixed. Here is one example where you might find it helpful:

`email=${username}@${domain}`

No need to make any changes, just wondering what your reasoning was

**Comment by mikedupuis** [comment]
Thank you so much for sending your PR. Please give the script a try and see if you like it!

**Pull request merged**
